### ISSUE TITLE
[fixed] macOS version working

### ISSUE THREAD

**Issue by flagsoft** [matteodelabre/mv7config#1]
While porting to macOS, I got this error. Any idea?

Data is sent to the device via integer array, right?

```
ret = function(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
ctypes.ArgumentError: argument 2: TypeError: wrong type
```

```
hid.HIDException: hid_read_timeout:  error waiting for more data
```

```python
% python3.11 ./repl.py
- found these devices:
{b'DevSrvsID:4294985165': {'path': b'DevSrvsID:4294985165', 'vendor_id': 5357, 'product_id': 4114, 'serial_number': '', 'release_number': 2, 'manufacturer_string': 'Shure Inc', 'product_string': 'Shure MV7', 'usage_page': 65280, 'usage': 1, 'interface_number': 3, 'bus_type': <BusType.USB: 1>}}
> su adm
data: su adm
comand: [115, 117, 32, 97, 100, 109]
comand2: [115, 117, 32, 97, 100, 109, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
Traceback (most recent call last):
  File "mv7config-main/./repl.py", line 65, in <module>
    main()
  File "mv7config-main/./repl.py", line 57, in main
    device.send_command(command)
  File "mv7config-main/mv7config/text_hid.py", line 47, in send_command
    self._hid.write( command2 )
  File "/usr/local/lib/python3.11/site-packages/hid/__init__.py", line 199, in write
    return self.__hidcall(hidapi.hid_write, self.__dev, data, len(data))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hid/__init__.py", line 186, in __hidcall
    ret = function(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
ctypes.ArgumentError: argument 2: TypeError: wrong type
    self.run()
  File "mv7config-main/./repl.py", line 20, in run
    message = self._device.read_message(timeout_ms=200)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mv7config-main/mv7config/text_hid.py", line 50, in read_message
    data = self._hid.read(64, timeout_ms)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hid/__init__.py", line 207, in read
    size = self.__hidcall(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hid/__init__.py", line 190, in __hidcall
    raise HIDException(err)
hid.HIDException: hid_read_timeout:  error waiting for more data
% 
```

**Comment by flagsoft** [comment]
fixed. I have a working macOS port now.

**Comment by matteodelabre** [comment]
Hey @flagsoft, that’s great! Did you need to make significant changes? Maybe we could get your work merged into this repo.

**Comment by flagsoft** [comment]
Ok, but note (NOTES for Linux and macOS):

### Linux compatibility (one single source for Linux and macOS version)

- **Maybe you can test my new code on your existing Linux machine/setup _before_ we do the repository merge? (for backwards compatibility, I think this is very important)**, here:
https://github.com/flagsoft/mv7config

Just set flag g__SUPPORT__hid_Device = False in file text_hid.py for your setup for compatibility.
The flag g__SUPPORT__hid_Device = True must be set if your Pythin hid interface use hid.Device(VID, PID) syntax not hid.device(). Maybe someone can do that programmatically.



### More notes about macOS version

- There is a native macOS version from the manufacturer itself from SHURE, but seems to be buggy and unstable and/or does not seems to work with MV7. I did not test this by myself. (I was able to get mv7config wokring for me on macOS Ventura, with Python 3.11 and HID native drivers for macOS.)



Check out my new code on your side first and test it, if it works on Linux, macOS...... whatever you have or need.

I used Python 3.11 because brew install and the python HID module was installed there. Python hid was installed on

```
/usr/local/lib/python3.11/site-packages/hid/__init__.py
```

macOS ative shared libararies somewhere else:
```
% brew install hidapi

% brew list hidapi                  
/usr/local/Cellar/hidapi/0.14.0/bin/hidtest
/usr/local/Cellar/hidapi/0.14.0/include/hidapi/ (2 files)
/usr/local/Cellar/hidapi/0.14.0/lib/libhidapi.0.14.0.dylib
/usr/local/Cellar/hidapi/0.14.0/lib/cmake/ (4 files)
/usr/local/Cellar/hidapi/0.14.0/lib/pkgconfig/hidapi.pc
/usr/local/Cellar/hidapi/0.14.0/lib/ (2 other files)

/usr/local/Cellar/hidapi/0.14.0/bin/hidtest
```




1.  In the file text_hid.py there is a file global FLAG:

```
## -- set this flag to True if your hid implementation supports hid.Device (capital D in Device)
g__SUPPORT__hid_Device = True
```

I depends on your target system, if your Phython HID "import hid" module supports the new hid.Device(VID, PID) syntax or not.

Maybe someone can check for this programmatically within the code later.


2. macOS HID installation
- Also for macOS there is no default HID implementation, one need to install and compile from source... not sure what all I did to make it work. There are many notes about this in my README.md

-> Maybe test my code on your side , set GLOBAL Flag to False and see if it still works (on your Linux setup). Ignoring the macOS part, if you can not test on macOS. 

Then I can do a pull request / merge.
